### ISSUE TITLE
dbマイグレーションの型付けのファイル容量を減らす

### ISSUE THREAD

**Issue by hibohiboo** [hibohiboo/kartagraph-monorepo#27]
全部パッケージングしているのでindex.jsがフクザツになっている。

**Comment by hibohiboo** [comment]
まずは、bundlingにzodを入れてみた。
レイヤーの更新を忘れたら、下記のエラーが出ているので、軽量化できたもよう。

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'zod'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'zod'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

**Comment by hibohiboo** [comment]
レイヤーを更新したら、無事に成功。
つぎに、スキーマファイルのレイヤ分けができないか試してみる。

**Comment by hibohiboo** [comment]
```
{
    "errorType": "Error",
    "errorMessage": "require() of ES Module /opt/nodejs/index.js from /var/task/index.js not supported.\n/opt/nodejs/index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which declares all .js files in that package scope as ES modules.\nInstead either rename /opt/nodejs/index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change \"type\": \"module\" to \"type\": \"commonjs\" in /opt/nodejs/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).\n",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/nodejs/index.js from /var/task/index.js not supported.",
        "/opt/nodejs/index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which declares all .js files in that package scope as ES modules.",
        "Instead either rename /opt/nodejs/index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change \"type\": \"module\" to \"type\": \"commonjs\" in /opt/nodejs/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).",
        "",
        "    at Object.<anonymous> (/var/task/index.js:46:21)"
    ]
}

```

設定ミスで上記エラーが発生
`

**Comment by hibohiboo** [comment]
type module にしたら下記のエラーが発生。

```
"require() of ES Module /opt/nodejs/index.js from /var/task/index.js not supported.\n/opt/nodejs/index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which declares all .js files in that package scope as ES modules.\nInstead either rename /opt/nodejs/index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change \"type\": \"module\" to \"type\": \"commonjs\" in /opt/nodejs/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).\n",
```

**Comment by hibohiboo** [comment]
原因は、 backend/package.json に type:"module"が入っており、requireを読み込めないことだった。
フロントエンドのpackage.jsonをコピーしたときに混入したものと思われる。
削除することで解決。
